---
title: "beginning.qmd"
format: pdf
editor: visual
---

3\.

```{r}
a = 1
b = -1
c = -2


quadratic = function(a, b, c) {
  discriminant <- (b ^ 2) - (4 * a * c)
  result1 = (-b + sqrt(discriminant)) / (2 * a)
  result2 = (-b - sqrt(discriminant)) / (2 * a)
  result = c(result2,result1)
 
  return(result)
}


quadratic(1,-1,-2)
```

4\.

```{r}
x <- seq(-5, 5, length = 100)

fx <- a * x^2 + b * x + c

plot(x,fx)

lines(x, rep(0, length(x)), col = "red", lty = 2)
```

5\.
```
#click renderon the beginning.qmd top and then use 
#mv beginning.pdf docs/
```

6\.
```
#mkdir data
#mkdir results
```


7\.
```
#cd data
#nano coefs1.txt
#1 -1 -2
```


8\.
```
#pwd
#cd ..
#mkdir code
#cpcp beginning.qmd code/quadratic.qmd
```

10\.
As by the problem, i changed the file path to the RtmpyDknq4 folder and then render it. It says cannot render it, since it wrong path. after changed it into relative path, it works again. And for the file.path(getwd(), "data/coefs.txt") please see the quadratic.qmd for the right path.